### PR TITLE
Add codeclimate report and add ruby 2.6.5 to test matrix

### PR DESCRIPTION
**Pull request by gmcculloug**
Copy CodeClimate config file from catalog-api.
Add Ruby 2.6.5 to travis test matrix.

### CODE REVIEW

**Review by eclarizio — APPROVED** [review]
Seems fine to me but do we run CodeClimate on this repo? (Or catalog-api, even?) Shouldn't there be a "CodeClimate" check next to Travis and Hakiri? Maybe they're not enabled right now or something, I don't think I have visibility into that at the moment.

**Comment by gmcculloug** [comment]
Right now there are badges on the [README.md](https://github.com/RedHatInsights/catalog-api-minion/blob/master/README.md).  We are working to enable more integration, like pass/fail checks on each PR and if coverage drops.

**Comment by gmcculloug** [comment]
@eclarizio I updated ruby versions to match related repos.
```json
rvm:
- 2.5.7
- 2.6.5
```

**Review by syncrou — APPROVED** [review]
LGTM 👍

**Pull request merged**
