### PR TITLE
Sprint 51 Hotfix #1 merge to stable

### PR DESCRIPTION
**Pull request by eclarizio**

### CODE REVIEW

**Comment by gmcculloug** [comment]
@eclarizio Do we need the second commit?

**Comment by eclarizio** [comment]
@gmcculloug Uh, I don't know, I just did a compare against master/stable and hit the button, I let git figure out the commits. I did it as if it were a sprint merge to stable since I knew there was only one, should I have just made a branch and cherry-picked?

**Comment by gmcculloug** [comment]
Looks like it is just the merge commit to master, but seems odd to have here.  I would prefer not include it in the PR.  Not sure if there is another way to handle it, but doing a cherry-pick would work.

**Comment by eclarizio** [comment]
Closed in favor of #37

**Pull request closed without merging**
